name: Deep Learning CI/CD Dry Run

on:
  push:
  workflow_dispatch:

jobs:
  dry-run-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
          pip install ultralytics
          pip install -r requirements.txt || echo "No requirements.txt found, skipping."

      - name: "Dry Run: Inference Script"
        run: |
          echo "Running dry run of Code/train_combined.py..."
          python train_combined.py || echo "Warning: train_combined.py failed (probably missing dataset)."

      - name: "Dry Run: Inference Script"
        run: |
          echo "Running dry run of Code/predict_combined.py..."
          python Code/predict_combined.py --source combined_videos.mp4 --weights Code/combined_detector_final_fresh4/weights/best.pt || echo "Warning: predict_combined.py failed (probably missing video or model)."
