name: Deep Learning Dry Run

on:
  push:
  workflow_dispatch:

jobs:
  dry-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
          pip install ultralytics
          pip install -r requirements.txt || echo "No requirements.txt found, skipping."

      - name: Dry Run Train Script
        run: |
          echo "Checking if train_combined.py runs without dataset..."
          python train_combined.py || echo "Warning: Training failed (probably missing dataset)."
